# Generated by Django 2.2.12 on 2021-05-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='OP',
        ),
    ]
