# Generated by Django 2.2.12 on 2021-05-17 12:42

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fase1new_group', to='otree.Session')),
            ],
            options={
                'db_table': 'Fase1NEW_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fase1new_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'Fase1NEW_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('quiz', otree.db.models.StringField(blank=True, choices=[['0', '12.28'], ['2', '9.78'], ['1', '16.53']], default='', max_length=10000, null=True, verbose_name='1. In base alla figura mostrata quale sarà il vostro guadagno se il reddito varierà del + 2%')),
                ('quiz2', otree.db.models.StringField(blank=True, choices=[['0', '19.03'], ['1', '9.78'], ['2', '10.78']], default='', max_length=10000, null=True, verbose_name='2.In base alla figura mostrata quale sarà il vostro guadagno se il reddito varierà del + 20%')),
                ('labelset', otree.db.models.IntegerField(default=0, null=True)),
                ('final_payment', otree.db.models.StringField(max_length=10000, null=True)),
                ('bin1', otree.db.models.IntegerField(default=0, null=True)),
                ('bin2', otree.db.models.IntegerField(default=0, null=True)),
                ('bin3', otree.db.models.IntegerField(default=0, null=True)),
                ('bin4', otree.db.models.IntegerField(default=0, null=True)),
                ('bin5', otree.db.models.IntegerField(default=0, null=True)),
                ('bin6', otree.db.models.IntegerField(default=0, null=True)),
                ('rep_1', otree.db.models.StringField(choices=[['RIPETERE', '1'], ['NO', '0']], default='', max_length=10000, null=True, verbose_name='')),
                ('rep_2', otree.db.models.StringField(choices=[['RIPETERE', '1'], ['NO', '0']], default='', max_length=10000, null=True, verbose_name='')),
                ('pref1', otree.db.models.IntegerField(default=0, null=True, verbose_name='')),
                ('pref2', otree.db.models.IntegerField(default=0, null=True, verbose_name='')),
                ('pref3', otree.db.models.IntegerField(default=0, null=True, verbose_name='')),
                ('sum_token', otree.db.models.FloatField(null=True)),
                ('w_amt', otree.db.models.FloatField(default=0, null=True, verbose_name='')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fase1NEW.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fase1new_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fase1new_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fase1NEW.Subsession')),
            ],
            options={
                'db_table': 'Fase1NEW_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fase1NEW.Subsession'),
        ),
    ]
