# Generated by Django 2.2.12 on 2021-05-19 09:51

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase1NEW', '0003_auto_20210517_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='player',
            name='quiz2',
        ),
        migrations.AddField(
            model_name='player',
            name='quiz2f1',
            field=otree.db.models.StringField(blank=True, choices=[['0', '12.44'], ['2', '14.94'], ['1', '13.69']], default='', max_length=10000, null=True, verbose_name='1. In base alla figura mostrata quale sarà il vostro guadagno se il reddito varierà del + 2%'),
        ),
        migrations.AddField(
            model_name='player',
            name='quiz3f1',
            field=otree.db.models.StringField(blank=True, choices=[['0', '17.44'], ['1', '14.94'], ['2', '13.69']], default='', max_length=10000, null=True, verbose_name='2.In base alla figura mostrata quale sarà il vostro guadagno se il reddito varierà del - 25%'),
        ),
        migrations.AddField(
            model_name='player',
            name='quiz4f1',
            field=otree.db.models.StringField(blank=True, choices=[['0', '17.44'], ['1', '14.94'], ['2', '13.69']], default='', max_length=10000, null=True, verbose_name='2.In base alla figura mostrata quale sarà il vostro guadagno se il reddito varierà del - 25%'),
        ),
        migrations.AddField(
            model_name='player',
            name='quizf1',
            field=otree.db.models.StringField(blank=True, choices=[['0', '12.44'], ['2', '14.94'], ['1', '13.69']], default='', max_length=10000, null=True, verbose_name='1. In base alla figura mostrata quale sarà il vostro guadagno se il reddito varierà del + 2%'),
        ),
    ]
