# Generated by Django 2.2.12 on 2021-05-20 15:41

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase1NEW', '0005_auto_20210520_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rip1',
            field=otree.db.models.StringField(blank=True, choices=[['0', 'Penso che questa allocazione rispecchi accuratamente la mia opinione, non voglio procedere con altre scelte'], ['1', 'Voglio procedere con ancora una scelta']], default='', max_length=10000, null=True),
        ),
    ]
