# Generated by Django 2.2.12 on 2021-05-20 16:00

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase1NEW', '0006_player_rip1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rip1',
            field=otree.db.models.StringField(blank=True, choices=[['0', 'Penso che questa allocazione rispecchi accuratamente la mia opinione, non voglio procedere con altre scelte'], ['1', 'Voglio procedere con ancora una scelta']], default='', max_length=10000, null=True, verbose_name=''),
        ),
    ]
