# Generated by Django 2.2.12 on 2021-05-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fase1NEW', '0012_auto_20210521_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='bin6',
        ),
    ]
