# Generated by Django 2.2.12 on 2021-05-23 13:34

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase1NEW', '0013_remove_player_bin6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='quiz2f1',
            field=otree.db.models.StringField(blank=True, choices=[['0', '19.06'], ['2', '14.06'], ['1', '11.56']], default='', max_length=10000, null=True, verbose_name='1. In base alla figura mostrata quale sarà il vostro guadagno se il reddito varierà del + 2%'),
        ),
        migrations.AlterField(
            model_name='player',
            name='quizf1',
            field=otree.db.models.StringField(blank=True, choices=[['0', '19.06'], ['2', '14.06'], ['1', '11.56']], default='', max_length=10000, null=True, verbose_name='1. In base alla figura mostrata quale sarà il vostro guadagno se il reddito varierà del + 2%'),
        ),
    ]
