# Generated by Django 2.2.12 on 2021-05-24 10:05

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase1NEW', '0018_auto_20210524_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='sum_token',
            field=otree.db.models.FloatField(default=5, null=True),
        ),
    ]
