# Generated by Django 2.2.12 on 2021-05-24 15:48

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase1NEW', '0019_auto_20210524_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='quiz2f1',
            field=otree.db.models.StringField(choices=[['0', '19.06'], ['2', '14.06'], ['1', '11.56']], default='', max_length=10000, null=True, verbose_name='1. In base alla figura mostrata quale sarà il vostro guadagno se il reddito varierà del + 2%'),
        ),
        migrations.AlterField(
            model_name='player',
            name='quiz4f1',
            field=otree.db.models.StringField(choices=[['0', '17.44'], ['1', '14.94'], ['2', '13.69']], default='', max_length=10000, null=True, verbose_name='2. In base alla figura mostrata quale sarà il vostro guadagno se il reddito varierà del - 25%'),
        ),
        migrations.AlterField(
            model_name='player',
            name='quizf1',
            field=otree.db.models.StringField(choices=[['0', '19.06'], ['2', '14.06'], ['1', '11.56']], default='', max_length=10000, null=True, verbose_name='1. In base alla figura mostrata quale sarà il vostro guadagno se il reddito varierà del + 2%'),
        ),
    ]
