# Generated by Django 2.2.12 on 2021-05-24 18:12

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase1NEW', '0021_auto_20210524_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rip1',
            field=otree.db.models.StringField(choices=[['0', 'Penso che questa allocazione rispecchi accuratamente la mia opinione, non voglio procedere con altre allocazioni'], ['1', 'Voglio procedere con una seconda allocazione']], default='', max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='rip2',
            field=otree.db.models.StringField(choices=[['0', 'Penso che questa allocazione rispecchi accuratamente la mia opinione, non voglio procedere con altre allocazioni'], ['1', 'Voglio procedere con una terza allocazione']], default='', max_length=10000, null=True, verbose_name=''),
        ),
    ]
