# Generated by Django 2.2.12 on 2021-05-24 18:13

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase1NEW', '0022_auto_20210524_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pref1',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=6, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='pref2',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=6, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='pref3',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=6, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='sum_token',
            field=otree.db.models.FloatField(default=18, null=True),
        ),
    ]
