# Generated by Django 2.2.12 on 2021-05-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fase1NEW', '0024_auto_20210525_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='quiz3f1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='quiz4f1',
        ),
    ]
