# Generated by Django 2.2.12 on 2021-05-14 14:57

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase2NEW', '0005_auto_20210514_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='quiz2',
            field=otree.db.models.StringField(blank=True, choices=[['0', '18168.49'], ['1', '18168.49'], ['2', '10.78']], default='', max_length=10000, null=True, verbose_name='2.In base alla figura mostrata quale sarà il vostro guadagno se la variazione sarà del - 20%'),
        ),
    ]
