# Generated by Django 2.2.12 on 2021-05-14 15:09

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase2NEW', '0010_auto_20210514_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='quiz3',
            field=otree.db.models.StringField(blank=True, choices=[['0', '€ 20720.34'], ['1', '€ 19394.07'], ['2', '€ 25518.52']], default='', max_length=10000, null=True, verbose_name='1. In base alla figura mostrata quale sarà il vostro guadagno se la variazione sarà del - 8%'),
        ),
        migrations.AlterField(
            model_name='player',
            name='quiz4',
            field=otree.db.models.StringField(blank=True, choices=[['0', '€ 18072.49'], ['2', '€ 20624.34'], ['1', '€ 23477.04']], default='', max_length=10000, null=True, verbose_name='2.In base alla figura mostrata quale sarà il vostro guadagno se la variazione sarà del  +12%'),
        ),
    ]
