# Generated by Django 2.2.12 on 2021-05-20 08:03

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase2NEW', '0016_auto_20210519_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='HL_11',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_12',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_13',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
    ]
