# Generated by Django 2.2.12 on 2021-05-20 12:18

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase2NEW', '0019_auto_20210520_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='quiz3',
            field=otree.db.models.StringField(blank=True, choices=[['2', '21436 €'], ['1', '17353 €'], ['2', '18383 €']], default='', max_length=10000, null=True, verbose_name='In base alla figura mostrata quale sarà il vostro guadagno se la variazione sarà del - 8%?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='quiz4',
            field=otree.db.models.StringField(blank=True, choices=[['2', '21436 €'], ['1', '17353 €'], ['2', '18383 €']], default='', max_length=10000, null=True, verbose_name='In base alla figura mostrata quale sarà il vostro guadagno se la variazione sarà del  -8%?'),
        ),
    ]
