# Generated by Django 2.2.12 on 2021-05-28 12:48

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase2NEW', '0025_auto_20210528_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='quiz',
            field=otree.db.models.StringField(choices=[['1', '20444 €'], ['2', '16361 €'], ['2', '21436 €']], default='', max_length=10000, null=True, verbose_name='In base alla figura mostrata, quale sarà il suo guadagno se la variazione sarà tra +1% e +10%?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='quiz2',
            field=otree.db.models.StringField(choices=[['1', '20444 €'], ['2', '16361 €'], ['2', '21436 €']], default='', max_length=10000, null=True, verbose_name='In base alla figura mostrata quale sarà il suo guadagno se la variazione sarà tra +1% e +10%?'),
        ),
    ]
