# Generated by Django 2.2.12 on 2021-06-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fase2NEW', '0026_auto_20210528_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='HL',
        ),
    ]
